Repository CMU-313/nodebb-f24-codebb, pull requests merged in 2024-10, with the labels that each got.

#25 Backend changes to display endorsement next to the author of a post in a topic
  .mocharc.yml
  public/openapi/read/topic/topic_id.yaml
  src/api/posts.js
  src/posts/votes.js
  src/topics/posts.js
Labels: enhancement, size: m, Endorse, US2: endorse posts

#26 Endorse: Created unit tests to test the functionality of the endorsement feature
  test/topics.js
Labels: size: m, Endorse, US2: endorse posts

#31 Adding frontend repo installation to azure-deploy-f24.yml
  .github/workflows/azure-deploy-f24.yml
Labels: bug

#32 Moving install frontend step after nodebb setup in azure-deploy-f24.yml
  .github/workflows/azure-deploy-f24.yml
Labels: bug
